public class calculation {
    Public integer addition(integer x,integer y){
        integer z;
        z=x+y;
        return z;
    }
    public integer substraction(integer x,integer y){
        integer z;
        z=x-y;
        return z;
    }
    public integer multiplication(integer x,integer y){
        integer z;
        z=x*y;
        return z;
    }
    public integer division(integer x,integer y){
        integer z;
        z=x/y;
        return z;
    }
}